### ISSUE TITLE
Cannot create snapshot before deleting RDS instance

### ISSUE THREAD

**Issue by ingenieroariel** [terranodo/ansible-worldmap#1]
```
ok: [localhost]
 ___________________________________________________________
/ TASK: Delete postgres rds instance, but create a snapshot \
\ before doing so                                           /
 -----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/x/.ansible/tmp/ansible-tmp-1433546375.34-147069845747561/rds", line 2816, in <module>
    main()
  File "/home/x/.ansible/tmp/ansible-tmp-1433546375.34-147069845747561/rds", line 1012, in main
    invocations[module.params.get('command')](module, conn)
  File "/home/x/.ansible/tmp/ansible-tmp-1433546375.34-147069845747561/rds", line 714, in delete_db_instance_or_snapshot
    result = conn.delete_db_instance(instance_name, **params)
  File "/home/x/.ansible/tmp/ansible-tmp-1433546375.34-147069845747561/rds", line 443, in delete_db_instance
    result = self.connection.delete_db_instance(instance_name, **params)['DeleteDBInstanceResponse']['DeleteDBInstanceResult']['DBInstance']
TypeError: delete_db_instance() got an unexpected keyword argument 'final_snapshot_id'


FATAL: all hosts have already failed -- aborting
```

**Comment by flyte** [comment]
I've just hit this problem too.

**Comment by flyte** [comment]
I've done a PR on ansible-modules-core which fixes this bug. The solution will be to update Ansible once it's rolled into a release.

**Comment by ingenieroariel** [comment]
Thanks a lot @flyte. I fixed it locally by patching both boto and ansible and was able to keep going. It would be great to see a fix upstream.

**Comment by flyte** [comment]
You could also have separated out the snapshot and deletion into two actions. That's what I've had to do for now - making sure to tell the snapshot command to wait for completion!

```yaml
    - name: Take snapshot of RDS instance
      rds:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        command: snapshot
        instance_name: "{{ rds_db.instance.id }}"
        region: eu-west-1
        snapshot: "mysnapshot-{{ ansible_date_time.epoch }}"
        wait: yes
      register: rds_snapshot

    - name: Remove RDS instance
      rds:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        command: delete
        instance_name: "{{ rds_db.instance.id }}"
        region: eu-west-1
```
